name: Domination
version: '${project.version}'
main: domination.morey.main
api-version: 1.19
depend: [WorldGuard, Citizens]
commands:
  money:
    description: Vous montre votre monnaie
    permission-message: "§c§l(!) §cYou don't have permission to use this command."
    permission: domination.money
  gmoney:
    description: Vous permet de donner de l'argent à un joueur (admin)
    permission-message: "§c§l(!) §cYou don't have permission to use this command."
    permission: domination.gmoney
  gxp:
    description: Vous permet de donner de l'xp à un joueur (admin)
    permission-message: "§c§l(!) §cYou don't have permission to use this command."
    permission: domination.gxp
  gmana:
    description: Vous permet de donner des levels à un joueur (admin)
    permission-message: "§c§l(!) §cYou don't have permission to use this command."
    permission: domination.glevel
  xp:
    description: Vous montre votre xp
    permission-message: "§c§l(!) §cYou don't have permission to use this command."
    permission: domination.xp
  level:
    description: Vous montre votre level
    permission-message: "§c§l(!) §cYou don't have permission to use this command."
    permission: domination.level
  rankup:
    description: Vous permet de passer au grade supérieur
    permission-message: "§c§l(!) §cYou don't have permission to use this command."
    permission: domination.rankup
  stats:
    description: Vous montre vos stats
    permission-message: "§c§l(!) §cYou don't have permission to use this command."
    permission: domination.stats
  whereis:
    description: Vous montre où sont les pnjs ou lieux importants
    permission-message: "§c§l(!) §cYou don't have permission to use this command."
    permission: domination.whereis
  glevel:
    description: Vous permet de donner des levels à un joueur (admin)
    permission-message: "§c§l(!) §cYou don't have permission to use this command."
    permission: domination.glevel
  classe:
    description: Vous permet de choisir votre classe
    permission-message: "§c§l(!) §cYou don't have permission to use this command."
    permission: domination.classe
  golem:
    description: Vous permet de faire apparaitre un golem
    permission-message: "§c§l(!) §cYou don't have permission to use this command."
    permission: domination.golem